# Generated by Django 3.1.3 on 2020-12-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsApp', '0005_auto_20201203_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
