# Generated by Django 3.1.3 on 2020-12-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsApp', '0008_projects_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='country',
            field=models.CharField(default='Kenya', max_length=255),
        ),
    ]
