# Generated by Django 3.1.3 on 2020-12-03 09:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsApp', '0009_auto_20201203_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
