# Generated by Django 3.1.3 on 2020-12-03 13:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsApp', '0010_auto_20201203_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='country',
            field=django_countries.fields.CountryField(default='Kenya', max_length=2),
        ),
    ]
