# Generated by Django 3.1.3 on 2020-12-03 13:13

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('awwardsApp', '0010_auto_20201203_1254'),
    ]

