# Generated by Django 3.1.3 on 2020-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardsApp', '0012_auto_20201203_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
